function [layers, layerlab,actlayIdx] = get_layer_names(cnntype,minlay)
if nargin == 1
    minlay =0;
else

switch cnntype
    case {'resnet50' 'resnet50_abl' 'resnet50-sin' 'resnet50-blur-st'}
        layers = {'relu','layer1.0.relu','layer1.1.relu','layer1.2.relu','layer2.0.relu','layer2.1.relu','layer2.2.relu','layer2.3.relu',...
            'layer3.1.relu','layer3.2.relu','layer3.3.relu','layer3.4.relu','layer3.5.relu','layer4.0.relu','layer4.1.relu','layer4.2.relu','avgpool','fc'};
        layerlab = cellfun(@(x) strrep(x,'.relu',''),layers,'UniformOutput',false);
    case {'resnet152' 'resnet152UT'}
        layers = {'relu','layer1.0.relu','layer1.1.relu','layer1.2.relu','layer2.0.relu','layer2.1.relu','layer2.2.relu','layer2.3.relu', ...
            'layer3.0.relu','layer3.5.relu','layer3.11.relu','layer3.17.relu','layer3.23.relu','layer3.29.relu','layer3.35.relu',...
            'layer4.0.relu','layer4.1.relu','layer4.2.relu','avgpool'};
        layerlab = cellfun(@(x) strrep(x,'.relu',''),layers,'UniformOutput',false);
    case {'convnextL'}
        layers = {'features.1.0.block.4' 'features.1.1.block.4' 'features.1.2.block.4' 'features.3.0.block.4' ...
            'features.3.1.block.4' 'features.3.2.block.4' 'features.5.0.block.4' 'features.5.1.block.4' 'features.5.10.block.4' 'features.5.11.block.4'...
            'features.5.12.block.4' 'features.5.13.block.4' 'features.5.14.block.4' 'features.5.15.block.4' 'features.5.16.block.4' 'features.5.17.block.4'...
            'features.5.18.block.4'	'features.5.19.block.4'	'features.5.2.block.4' 'features.5.20.block.4' 'features.5.21.block.4' 'features.5.22.block.4'...
            'features.5.23.block.4'	'features.5.24.block.4'	'features.5.25.block.4'	'features.5.26.block.4'	'features.5.3.block.4'	'features.5.4.block.4'...
            'features.5.5.block.4'	'features.5.6.block.4'	'features.5.7.block.4'	'features.5.8.block.4'	'features.5.9.block.4'	'features.7.0.block.4'...
            'features.7.1.block.4'	'features.7.2.block.4' 'classifier.0' 'classifier.2'};
        layerlab = cellfun(@(x) strrep(x,'.block.4',''),layers,'UniformOutput',false);
    case {'vit_l_16'}
        layers = {'encoder.layers.encoder_layer_0.mlp.1','encoder.layers.encoder_layer_1.mlp.1', 'encoder.layers.encoder_layer_2.mlp.1', 'encoder.layers.encoder_layer_3.mlp.1',...
            'encoder.layers.encoder_layer_4.mlp.1','encoder.layers.encoder_layer_5.mlp.1','encoder.layers.encoder_layer_6.mlp.1','encoder.layers.encoder_layer_7.mlp.1',...
            'encoder.layers.encoder_layer_8.mlp.1','encoder.layers.encoder_layer_9.mlp.1','encoder.layers.encoder_layer_10.mlp.1','encoder.layers.encoder_layer_11.mlp.1',...
            'encoder.layers.encoder_layer_12.mlp.1','encoder.layers.encoder_layer_13.mlp.1','encoder.layers.encoder_layer_14.mlp.1','encoder.layers.encoder_layer_15.mlp.1',...
            'encoder.layers.encoder_layer_16.mlp.1','encoder.layers.encoder_layer_17.mlp.1','encoder.layers.encoder_layer_18.mlp.1','encoder.layers.encoder_layer_19.mlp.1',...
            'encoder.layers.encoder_layer_20.mlp.1','encoder.layers.encoder_layer_21.mlp.1','encoder.layers.encoder_layer_22.mlp.1','encoder.layers.encoder_layer_23.mlp.1',...
            'encoder.ln','heads.head'};
        layerlab = cellfun(@(x) strrep(x,'encoder.layers.encoder_',''),layers,'UniformOutput',false);
        layerlab = cellfun(@(x) strrep(x,'.mlp.1',''),layerlab,'UniformOutput',false);
    case {'cornet-s' 'cornet-s-blur-st'}
        layers ={'V1.nonlin1', 'V1.nonlin2', 'V2.nonlin1','V2.nonlin2', 'V2.nonlin3','V4.nonlin1','V4.nonlin2','V4.nonlin3','IT.nonlin1','IT.nonlin2','IT.nonlin3','decoder.avgpool','decoder.output'};
        layerlab = layers;
    case {'clip_vit-b_image'}
        layers = {'visual.transformer.resblocks.0.mlp.gelu','visual.transformer.resblocks.1.mlp.gelu','visual.transformer.resblocks.2.mlp.gelu',...
            'visual.transformer.resblocks.3.mlp.gelu','visual.transformer.resblocks.4.mlp.gelu','visual.transformer.resblocks.5.mlp.gelu',...
            'visual.transformer.resblocks.6.mlp.gelu','visual.transformer.resblocks.7.mlp.gelu','visual.transformer.resblocks.8.mlp.gelu',...
            'visual.transformer.resblocks.9.mlp.gelu','visual.transformer.resblocks.10.mlp.gelu','visual.transformer.resblocks.11.mlp.gelu',...
            'visual.ln_post'};
        layerlab = cellfun(@(x) strrep(x,'.mlp.gelu',''),layers,'UniformOutput',false);
        layerlab = cellfun(@(x) strrep(x,'visual.transformer.',''),layerlab,'UniformOutput',false);
    case {'clip_vit-l-laion_image'}
        layers = {'visual.transformer.resblocks.0.mlp.gelu','visual.transformer.resblocks.1.mlp.gelu','visual.transformer.resblocks.2.mlp.gelu',...
            'visual.transformer.resblocks.3.mlp.gelu','visual.transformer.resblocks.4.mlp.gelu','visual.transformer.resblocks.5.mlp.gelu',...
            'visual.transformer.resblocks.6.mlp.gelu','visual.transformer.resblocks.7.mlp.gelu','visual.transformer.resblocks.8.mlp.gelu',...
            'visual.transformer.resblocks.9.mlp.gelu','visual.transformer.resblocks.10.mlp.gelu','visual.transformer.resblocks.11.mlp.gelu',...
            'visual.transformer.resblocks.12.mlp.gelu','visual.transformer.resblocks.13.mlp.gelu','visual.transformer.resblocks.14.mlp.gelu',...
            'visual.transformer.resblocks.15.mlp.gelu','visual.transformer.resblocks.16.mlp.gelu','visual.transformer.resblocks.17.mlp.gelu',...
            'visual.transformer.resblocks.18.mlp.gelu','visual.transformer.resblocks.19.mlp.gelu','visual.transformer.resblocks.20.mlp.gelu',...
            'visual.transformer.resblocks.21.mlp.gelu','visual.transformer.resblocks.22.mlp.gelu','visual.transformer.resblocks.23.mlp.gelu',...
            'visual.ln_post' 'similarities'};
        layerlab = cellfun(@(x) strrep(x,'.mlp.gelu',''),layers,'UniformOutput',false);
        layerlab = cellfun(@(x) strrep(x,'visual.transformer.',''),layerlab,'UniformOutput',false);
    case {'clip_convnextL_image'}
        layers = {'visual.trunk.stages.0.blocks.0.mlp.act','visual.trunk.stages.0.blocks.1.mlp.act','visual.trunk.stages.0.blocks.2.mlp.act',...
            'visual.trunk.stages.1.blocks.0.mlp.act','visual.trunk.stages.1.blocks.1.mlp.act','visual.trunk.stages.1.blocks.2.mlp.act',...
            'visual.trunk.stages.2.blocks.0.mlp.act','visual.trunk.stages.2.blocks.1.mlp.act','visual.trunk.stages.2.blocks.2.mlp.act',...
            'visual.trunk.stages.2.blocks.3.mlp.act','visual.trunk.stages.2.blocks.4.mlp.act','visual.trunk.stages.2.blocks.5.mlp.act',...
            'visual.trunk.stages.2.blocks.6.mlp.act','visual.trunk.stages.2.blocks.7.mlp.act','visual.trunk.stages.2.blocks.8.mlp.act',...
            'visual.trunk.stages.2.blocks.9.mlp.act','visual.trunk.stages.2.blocks.10.mlp.act','visual.trunk.stages.2.blocks.11.mlp.act',...
            'visual.trunk.stages.2.blocks.12.mlp.act','visual.trunk.stages.2.blocks.13.mlp.act','visual.trunk.stages.2.blocks.14.mlp.act',...
            'visual.trunk.stages.2.blocks.15.mlp.act','visual.trunk.stages.2.blocks.16.mlp.act','visual.trunk.stages.2.blocks.17.mlp.act',...
            'visual.trunk.stages.2.blocks.18.mlp.act','visual.trunk.stages.2.blocks.19.mlp.act','visual.trunk.stages.2.blocks.20.mlp.act',...
            'visual.trunk.stages.2.blocks.21.mlp.act','visual.trunk.stages.2.blocks.22.mlp.act','visual.trunk.stages.2.blocks.23.mlp.act',....
            'visual.trunk.stages.2.blocks.24.mlp.act','visual.trunk.stages.2.blocks.25.mlp.act','visual.trunk.stages.2.blocks.26.mlp.act',...
            'visual.trunk.stages.3.blocks.0.mlp.act','visual.trunk.stages.3.blocks.1.mlp.act','visual.trunk.stages.3.blocks.2.mlp.act',...
            'visual.head.mlp.fc2' ,'similarities'};
        layerlab = cellfun(@(x) strrep(x,'.mlp.act',''),layers,'UniformOutput',false);
        layerlab = cellfun(@(x) strrep(x,'visual.trunk.',''),layerlab,'UniformOutput',false);
    case {'convnext_large_mlp:clip_laion2b_augreg_ft_in1k_384'}
        layers = {'stages.0.blocks.0.mlp.act','stages.0.blocks.1.mlp.act','stages.0.blocks.2.mlp.act',...
            'stages.1.blocks.0.mlp.act','stages.1.blocks.1.mlp.act','stages.1.blocks.2.mlp.act',...
            'stages.2.blocks.0.mlp.act','stages.2.blocks.1.mlp.act','stages.2.blocks.2.mlp.act',...
            'stages.2.blocks.3.mlp.act','stages.2.blocks.4.mlp.act','stages.2.blocks.5.mlp.act',...
            'stages.2.blocks.6.mlp.act','stages.2.blocks.7.mlp.act','stages.2.blocks.8.mlp.act',...
            'stages.2.blocks.9.mlp.act','stages.2.blocks.10.mlp.act','stages.2.blocks.11.mlp.act',...
            'stages.2.blocks.12.mlp.act','stages.2.blocks.13.mlp.act','stages.2.blocks.14.mlp.act',...
            'stages.2.blocks.15.mlp.act','stages.2.blocks.16.mlp.act','stages.2.blocks.17.mlp.act',...
            'stages.2.blocks.18.mlp.act','stages.2.blocks.19.mlp.act','stages.2.blocks.20.mlp.act',...
            'stages.2.blocks.21.mlp.act','stages.2.blocks.22.mlp.act','stages.2.blocks.23.mlp.act',....
            'stages.2.blocks.24.mlp.act','stages.2.blocks.25.mlp.act','stages.2.blocks.26.mlp.act',...
            'stages.3.blocks.0.mlp.act','stages.3.blocks.1.mlp.act','stages.3.blocks.2.mlp.act',...
            'head.pre_logits.act','head.fc'};
        layerlab = cellfun(@(x) strrep(x,'.mlp.act',''),layers,'UniformOutput',false);
    case {'vit_large_patch14_clip_224.laion2b_ft_in12k_in1k'}
        layers = {'blocks.0.mlp.act','blocks.1.mlp.act','blocks.2.mlp.act','blocks.3.mlp.act','blocks.4.mlp.act','blocks.5.mlp.act',...
            'blocks.6.mlp.act','blocks.7.mlp.act','blocks.8.mlp.act','blocks.9.mlp.act','blocks.10.mlp.act','blocks.11.mlp.act',...
            'blocks.12.mlp.act','blocks.13.mlp.act','blocks.14.mlp.act','blocks.15.mlp.act','blocks.16.mlp.act','blocks.17.mlp.act',...
            'blocks.18.mlp.act','blocks.19.mlp.act','blocks.20.mlp.act','blocks.21.mlp.act','blocks.22.mlp.act','blocks.23.mlp.act'...
            'norm' 'head'};
        layerlab = cellfun(@(x) strrep(x,'.mlp.act',''),layers,'UniformOutput',false);
end
layerlab = cellfun(@(x) strrep(x,'_','\_'),layerlab,'UniformOutput',false);

actlayIdx = contains(layers,'relu')|contains(layers,'.mlp.act')|contains(layers,'.block.4')|contains(layers,'.mlp.1')|...
    contains(layers,'nonlin')|contains(layers,'.mlp.gelu');

if minlay
    tmp = find(actlayIdx);
    valLayIdx = [tmp(1) ceil(length(layers)/2) tmp(end) length(layers)-1];
    layers = layers(valLayIdx);
    layerlab = layerlab(valLayIdx);
end
end